# Generated by Django 4.2.1 on 2024-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("violation_type", models.CharField(max_length=100)),
                (
                    "fine_collected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField()),
                ("vehicle_number", models.CharField(max_length=20)),
                ("officer_name", models.CharField(max_length=100)),
            ],
        ),
    ]
