# Generated by Django 4.2.1 on 2024-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_violationtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="violation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="violations/"),
        ),
    ]
